only test against LTS versions
According to https://endoflife.date/java,
the security support ended
- for Java  9 on 20 Mar 2018
- for Java 10 on 25 Sep 2018
- for Java 12 on 17 Sep 2019
- for Java 13 on 17 Mar 2020
- for Java 14 on 16 Sep 2020
- for Java 15 on 16 Mar 2021
- for Java 16 on 14 Sep 2021

Weirdly, for JDK 10 on Ubuntu, one test had suddenly started to fail:

```
ModulePathTest > can_find_class_on_the_modulepath() FAILED
    com.tngtech.archunit.thirdparty.com.google.common.util.concurrent.UncheckedExecutionException: java.util.ConcurrentModificationException
        at app/com.tngtech.archunit@1.1.0-SNAPSHOT/com.tngtech.archunit.thirdparty.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2055)
        at app/com.tngtech.archunit@1.1.0-SNAPSHOT/com.tngtech.archunit.thirdparty.com.google.common.cache.LocalCache.get(LocalCache.java:3966)
        at app/com.tngtech.archunit@1.1.0-SNAPSHOT/com.tngtech.archunit.thirdparty.com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4863)
        at app/com.tngtech.archunit@1.1.0-SNAPSHOT/com.tngtech.archunit.core.importer.Location.streamEntries(Location.java:150)
        at app/com.tngtech.archunit@1.1.0-SNAPSHOT/com.tngtech.archunit.core.importer.Locations.containsEntryWithPrefix(Locations.java:145)
        at app/com.tngtech.archunit@1.1.0-SNAPSHOT/com.tngtech.archunit.core.importer.Locations.getResourceLocations(Locations.java:129)
        at app/com.tngtech.archunit@1.1.0-SNAPSHOT/com.tngtech.archunit.core.importer.Locations.getLocationsOf(Locations.java:115)
        at app/com.tngtech.archunit@1.1.0-SNAPSHOT/com.tngtech.archunit.core.importer.Locations.ofPackage(Locations.java:75)
        at app/com.tngtech.archunit@1.1.0-SNAPSHOT/com.tngtech.archunit.core.importer.ClassFileImporter.lambda$importPackages$1(ClassFileImporter.java:212)
        at java.base@10.0.2/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
        at java.base@10.0.2/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base@10.0.2/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base@10.0.2/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base@10.0.2/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base@10.0.2/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base@10.0.2/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base@10.0.2/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at app/com.tngtech.archunit@1.1.0-SNAPSHOT/com.tngtech.archunit.core.importer.ClassFileImporter.importPackages(ClassFileImporter.java:213)
        at app/com.tngtech.archunit@1.1.0-SNAPSHOT/com.tngtech.archunit.core.importer.ClassFileImporter.importPackages(ClassFileImporter.java:225)
        at app/example_module@1.1.0-SNAPSHOT/com.tngtech.archunit.example.ModulePathTest.can_find_class_on_the_modulepath(ModulePathTest.java:21)

        Caused by:
        java.util.ConcurrentModificationException
            at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:937)
            at java.base/java.util.ArrayList$Itr.next(ArrayList.java:891)
            at java.base/java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1043)
            at java.base/jdk.internal.module.SystemModuleFinders$ModuleContentSpliterator.next(SystemModuleFinders.java:522)
            at java.base/jdk.internal.module.SystemModuleFinders$ModuleContentSpliterator.tryAdvance(SystemModuleFinders.java:549)
            at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:326)
            at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
            at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
            at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
            at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
            at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
            at com.tngtech.archunit@1.1.0-SNAPSHOT/com.tngtech.archunit.core.importer.ModuleLocationFactory$ModuleLocation.lambda$readResourceEntries$0(ModuleLocationFactory.java:108)
            at com.tngtech.archunit@1.1.0-SNAPSHOT/com.tngtech.archunit.core.importer.ModuleLocationFactory.doWithModuleReader(ModuleLocationFactory.java:49)
            at com.tngtech.archunit@1.1.0-SNAPSHOT/com.tngtech.archunit.core.importer.ModuleLocationFactory.access$000(ModuleLocationFactory.java:36)
            at com.tngtech.archunit@1.1.0-SNAPSHOT/com.tngtech.archunit.core.importer.ModuleLocationFactory$ModuleLocation.readResourceEntries(ModuleLocationFactory.java:105)
            at com.tngtech.archunit@1.1.0-SNAPSHOT/com.tngtech.archunit.thirdparty.com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4868)
            at com.tngtech.archunit@1.1.0-SNAPSHOT/com.tngtech.archunit.thirdparty.com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533)
            at com.tngtech.archunit@1.1.0-SNAPSHOT/com.tngtech.archunit.thirdparty.com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282)
            at com.tngtech.archunit@1.1.0-SNAPSHOT/com.tngtech.archunit.thirdparty.com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159)
            at com.tngtech.archunit@1.1.0-SNAPSHOT/com.tngtech.archunit.thirdparty.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
            ... 19 more
```

We never found out the concrete reason, but it seems to be some bug in combination with this concrete old JDK 10 version and the environment, since the same test with the same JDK seems to run fine locally. Nevertheless, it's not worth it anymore to invest energy in fixing problems with an ancient JDK that has long no support or users anymore.

Signed-off-by: Manfred Hanke <Manfred.Hanke@tngtech.com>