Added ImportedClasses to BuilderWithBuildParameters.build(..), so that JavaMembers can resolve types from the imported context. Thus often TypeDetails was replaced by a full JavaClass. Also fixed shadowJar for testJar, since the testJar didn't contain relocated classes and thus accessing asm.Type caused NoClassDefFoundErrors when running the tests.